name: CI / Verify Assets

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify Assets
        run: echo Assets Verified | base64

      - name: End the Job
        run: |
          sudo apt install neofetch figlet
          figlet Welcome to CLI.
          neofetch
