name: CI / Bundle Icons

on: [push]

jobs:
  bundle-svg-files:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Create Directory
      run: mkdir bundled_icons

    - name: Find and copy SVG files
      run: |
        ls -al
        find . -name "*.svg" -exec cp {} bundle_icons/ \;
      shell: bash

    - name: Verify SVG files
      run: ls bundled_icons

    - name: Upload bundled SVGs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: bundled_icons
        path: bundled_icons
