name: CI / Bundle Icons

on: 
  schedule:
    - cron: '0 0 * * 0'
  push:
     branches: "master"
  workflow_dispatch:
    
jobs:
  bundle-svg-files:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: [18.x, 19.x, 20.x, 21.x, 22.x]
    steps:
    - name: Checkout Icons
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Create Directory
      run: mkdir bundled_icons

    - name: Find and copy SVG files
      run: |
        ls -al
        find . -name "*.svg" -exec cp {} bundle_icons/ \;
      shell: bash

    - name: Verify SVG files
      run: ls bundled_icons

    - name: Upload bundled SVGs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: bundled_icons
        path: bundled_icons

    - name: Cleanup
      run: echo "Job Finished" | base64