name: CI / Maintenance

on:
  schedule:
  - cron: '45 23 * * *'
  push:
    branches:
      - master

jobs:
  updates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Add Updates
      run: |
        for dir in $(find . -type d ! -path .); do
          echo "Adding README.md to $dir"
          echo "# README" > $dir/README.md
          echo "This is the README file for the $(basename $dir) directory." >> $dir/README.md
          echo "Date: $(date '+%Y-%m-%d')" >> $dir/README.md
        done

    - name: Commit changes
      run: |
        git config --global user.name 'npm-run-test'
        git config --global user.email 'node_modules@hotmail.com'
        git add .
        git commit -m "Update README.md files with current date

        
        Signed-off-by: node_module [bot] <node_modules@hotmail.com> 
        Co-Authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
      continue-on-error: true

    - name: Push changes
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
