name: CI / Mirror Sync
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: ['**']
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Repo Sync
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: ${{ secrets.TARGET_URL }}
          target-username: ${{ secrets.TARGET_USER }}
          target-token: ${{ secrets.TARGET_TOKEN }}