name: CI / Mirror Sync
on:
  push:
    branches: ['**']
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Repo Sync
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: offensive-vk/auto-repo-sync@master
        with:
          target-url: ${{ secrets.TARGET_URL }}
          target-username: ${{ secrets.TARGET_USER }}
          target-token: ${{ secrets.TARGET_TOKEN }}